version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo-markdown
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
